### ISSUE TITLE
App name is always created as 'dooboo'

### ISSUE THREAD

**Issue by breakstone81** [dooboolab/dooboo-cli#10]
Above all, thank you for the update.

I installed 'dooboo-cli 1.4.0'
And I used **React Native App (typescript, context-api)** mode
In this case, an app is always created with the name 'dooboo'.
**The name of the directory is correct, but the app's name is always 'dooboo'.**
The 1.3.x version and Legacy Mode operate correctly.
Thank you.

**Comment by hyochan** [comment]
@breakstone81 Sorry about this. There must be a regression. I will fix this today. Thank you.

**Comment by hyochan** [comment]
I've made the fix in #11. Please try again.

**Comment by breakstone81** [comment]
I have Checked it.
It works exactly.
Thanks for your attention.
