### ISSUE TITLE
package.json keywords field may help increase of downloads.

### ISSUE THREAD

**Issue by ZeroCho** [dooboolab/dooboo-cli#3]
Currently, there's no keyword at all. If we set some keywords in package.json, it would be better for people to find dooboolab packages.

Some keywords I suggest are react, react-native, typescript, flow, mobx, boilerplate, cli, template.

[Keywords doc](https://docs.npmjs.com/files/package.json#keywords)

**Comment by hyochan** [comment]
Good point. Would you like to start the `PR` from this?

**Comment by ZeroCho** [comment]
#5
