### ISSUE TITLE
'dooboo init' command not working correctly if Cocoapods is not installed.

### ISSUE THREAD

**Issue by JongtaekChoi** [dooboolab/dooboo-cli#34]
When I have not installed Cocoapods and tried to initialize rn project, dooboo-cli asked me if I want to install Cocoapods. But the program did not respond even if I pressed Y key or n key or any other keys. Of course, it worked normally after I installed Cocoapods on it. But, I think we need to add a notice to the README.md file that asks us to install the cocoa pod first.

**Comment by hyochan** [comment]
Thanks for the report! I hope this will be fixed in `2.0.0`.
