### ISSUE TITLE
Removing path and fs as dependencies.

### ISSUE THREAD

**Issue by ZeroCho** [dooboolab/dooboo-cli#4]
Is there any special reason for using npm's path and fs modules rather than default ones node provides?

[path](https://github.com/dooboolab/dooboo-cli/blob/master/package.json#L21)
[fs](https://github.com/dooboolab/dooboo-cli/blob/master/package.json#L18)
can be removed, so that dooboo-cli use native modules node provides.

**Comment by hyochan** [comment]
Again good point. I was willing to ensure that they are `installed` correctly as discussed in [issue](https://github.com/jinder/path/issues/7). However, if you are confident that those are not needed we can get that away!

**Comment by ZeroCho** [comment]
#5

**Comment by ZeroCho** [comment]
Moreover, path & fs modules currently installed are out of date(almost 3~4 yrs). Way better use default  modules node provides

**Comment by hyochan** [comment]
Just released `1.2.1` with this update. Let's see how it goes.
Thanks for the `PR`. The first one to contribute to `dooboo-cli`!
