### ISSUE TITLE
Warning: Accesing view manager configs for getConstants

### ISSUE THREAD

**Issue by devohno** [dooboolab/dooboo-cli#52]
Related with [this issues](https://github.com/kmagiera/react-native-gesture-handler/issues/742)

I tried to Expo project with `dooboo-cli` first time.

After then, this warning appears.

`Accessing view manager configs directly off UIManager via UIManager['getConstants'] is no longer supported. Use UIManager.getViewManagerConfig('getConstants') instead.`

So I did like this.

1. `yarn remove react-native-gesture-handler`
2. `expo install react-native-gesture-handler`
3. `dooboo start`

Then, the warning is not appears to me.

**Comment by hyochan** [comment]
Thanks for the issue. [This update](https://github.com/dooboolab/dooboo-expo/commit/9b21a6bde38010233687008f71819658fdeb2678) will fix it!
