### ISSUE TITLE
android build.gradle The code applicationId generated using scaffolding is not modified and cannot be used normally.

### ISSUE THREAD

**Issue by YahuiWong** [dooboolab/dooboo-cli#6]
The code applicationId generated using scaffolding is not modified and cannot be used normally.

![image](https://user-images.githubusercontent.com/32868945/50351740-0b976480-057e-11e9-91e6-b680bf3171b7.png)

**Comment by YahuiWong** [comment]
no, i am using mac……

**Comment by hyochan** [comment]
@YahuiWong Could you tell me which was your `applicationId`? I may have to check `regex` rule for your strings.

**Comment by YahuiWong** [comment]
react native project name:rntsapp
applicationId:com.rntsapp

**Comment by hyochan** [comment]
@YahuiWong I've just tried this with `react-native app with flow` and it worked fine.
![image](https://user-images.githubusercontent.com/27461460/50432641-94175b80-0916-11e9-9423-bbb00bc03ca9.png)

Could you try again and tell me which option you've chosen to create the project (react-native-typescript? react-flow?)?

**Comment by YahuiWong** [comment]
React Native App Typescript

**Comment by hyochan** [comment]
@YahuiWong Fixed. Thanks for the issue!.
