### ISSUE TITLE
lint error

### ISSUE THREAD

**Issue by bumjoo** [dooboolab/dooboo-cli#71]
Hello.

I just created a react project using dooboo-cli (v3.6.1), installed the package, and ran yarn lint.
Then I got several errors as below.

```
    1:8  error  'React' was used before it was defined  no-use-before-define
```

I didn't change any codes after creating a project using dooboo-cli.

How can I fix them ?

**Comment by hyochan** [comment]
@bumjoo Sorry for the delay! I think this is now fixed. Please feel free to reopen when you still face the issue.
