### ISSUE TITLE
About using npx to initialize a react-native app

### ISSUE THREAD

**Issue by JongtaekChoi** [dooboolab/dooboo-cli#72]
It is recommended officially at the react-native document site. 
And installed global `react-native-cli` package may cause unexpected issues when using `react-native-cli` with npx.
So I think that we should use npx to initialize react-native apps and stop requiring install 'react-native-cli' globally.

**Comment by hyochan** [comment]
We'll consider this. Maybe we can install `react-native-cli` to `dooboo-cli` locally.

**Comment by hyochan** [comment]
Thanks for the issue! This is fixed in [4.0.0](https://www.npmjs.com/package/dooboo-cli/v/4.0.0)
