### ISSUE TITLE
Still generate 'enzyme' test code in TypeScript mode.

### ISSUE THREAD

**Issue by breakstone81** [dooboolab/dooboo-cli#8]
1. install **dooboo-cli**
1. run **dooboo init**
1. select **React Native App (typescript, mobx)** or **Expo App (typescript, mobx)**
1. run **dooboo screen Login**
1. then *enzyme* test code has generated in **Login.test.tsx**

* Need I install **enzyme** manually?
* my **dooboo-cli** version is **1.3.0**
* **flow mode** have not this issue.

**Comment by hyochan** [comment]
Thanks for using `dooboo-cli`. I've just updated template in `1.3.3`.
